### ISSUE TITLE
rdugpi.py

### ISSUE THREAD

**Issue by jabbalaci** [gelleicsaba/aoc#1]
Hello,

You should have a `main()` function. Now everything is in the global namespace, which is not a good idea. I use this sample program when I write a new Python script:

```python
#!/usr/bin/env python3

def main():
    print("Py3")

##############################################################################

if __name__ == "__main__":
    main()
```

And you have a typo: dictionery -> dictionary

**Comment by gelleicsaba** [comment]
Hi
I fixed it, and I've also installed this extension:
[https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).

**Comment by jabbalaci** [comment]
I'll try this VS Code extension. Thanks for the tip.
