### ISSUE TITLE
subdirectories

### ISSUE THREAD

**Issue by jabbalaci** [gelleicsaba/aoc#2]
Inside the folder `2024`, create subdirectories for each day: `day01`, `day02`, etc. Now everything is thrown together.

**Comment by gelleicsaba** [comment]
I fixed in this folder. 
I've noticed this must be done in another folders too (2015,2016, ...).
The empty export ('export {}') in the beginning of the .ts files are unnecessary. I still have to fix these.

**Comment by jabbalaci** [comment]
It's enough to fix the `2024` folder.
